version: "3.7"
services:
#  app:
##    command:
##      - ./mvnw spring-boot:build-image -fn
#    image: youtube-spring-boot-image
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#    restart: always
  postgres:
    image: postgres:alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=posts
    restart: unless-stopped

volumes:
  postgres-data: