
spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true
        max-page-size: 50

  profiles:
    active: dev
---

spring:
  profiles: dev
  devtools:
    remote:
      secret: "mysecret"
  datasource:
    username: postgres
    url: jdbc:postgresql://postgres:5432/posts
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  mvc:
    throw-exception-if-no-handler-found: 'true'